image: golang

stages:
  - test
  - build
before_script:
  - export GOPATH=/cache/go
  - go get -u golang.org/x/lint/golint
  - apt-get update && apt-get install -y make curl


unit_tests:
  stage: test
  script:
    - go test -cover $(go list  ./... | grep -v /vendor/)

lint_code:
  stage: test
  allow_failure: true
  script:
    - golint -set_exit_status $(go list ./... | grep -v /vendor/)

build:
  stage: build
  script:
    - go build cmd/wtfd.go
  artifacts:
    paths:
      - wtfd
      - html/*
      - challs.json
